Minor enhancement for PowerShell script and gitignore file
substation-beta/ssb_implementation pull request #1
Opened 2021-02-14 14:29 UTC by Doko-Demo-Doa

# Purpose
This PR updates PowerShell script used for pipeline and/or environment setup.

# Changes
- `vapoursynth64-install.ps1` now uses `curl`, since PowerShell 7 (and up) doesn't come with `wget` by default. Using `curl` ensures more shells may run the script successfully.

- 7z extract command will now excludes `7z.exe` and `7z.dll` files inside `VapourSynth64-Portable-R52.7z` archive. I used [miniconda3](https://docs.conda.io/en/latest/miniconda.html) to install Python and its tools. However miniconda3 includes 7z executable file by default and expose itself in PATH (same folder with its bundled Python version), which cause an error after extraction (`7z.exe` in 7z file attempts to replace __running__ `7z.exe` in miniconda directory).

- Cleanup after extraction and gitignore minor additions.

# Checklist
- [x] Followed contributing guidelines
- [x] Guaranteed appropriate quality of code
- [ ] Updated documentation (?)
- [x] Successfully tested
- [x] Self-reviewed changes

2021-02-23 23:41 UTC, Youka requested changes

2021-02-23 23:41 UTC, Youka commented on .gitignore
> +utfile
For what was `utfile` generated? And does it need to be in project folder?

2021-02-23 23:41 UTC, Youka commented on .gitignore
> +VapourSynth**.7z
Vapoursynth installation happens in project folder for convenience by continuous integration but doesn't need to be that way for the usual workflow.
Location of _VapourSynth**.7z_ isn't required to be here.

2021-02-23 23:41 UTC, Youka commented on .scripts/vapoursynth64-install.ps1
> +Invoke-WebRequest https://github.com/vapoursynth/vapoursynth/releases/download/R52/VapourSynth64-Portable-R52.7z -OutFile "VapourSynth64-Portable-R52.7z"
Quotes required?

2021-02-23 23:41 UTC, Youka commented on .scripts/vapoursynth64-install.ps1
> +7z x VapourSynth64-Portable-R52.7z -o"$Env:PYTHON" -y '-xr!7z.*'
Please comment why you exclude 7z binaries from extraction.

2021-02-23 23:41 UTC, Youka commented on .scripts/vapoursynth64-install.ps1
> +Remove-Item VapourSynth64-Portable-R52.7z
CI workspace gets dropped after workflow anyway. This step isn't necessary.

2022-01-11 12:22 UTC, Doko-Demo-Doa commented
It seems that this PR is no longer necessary since it only solve miniconda's case. Sorry for late response (I didn't turn on the notification).

2022-01-11 12:22 UTC, closed without merging